* use-package-secret

** Extend use-package to set symbols from external files

This extension allows configuration of symbols from external files so
emacs init files may be made public but usernames, passwords, access
tokens, and other sensitive information may be used for configuration
but kept private.

** Usage

This package loads the contents of certain files, by default in
’{$user-emacs-dir}/{$package-name}/secret.el’, to plist symbols, with some
error-checking. Individual symbols are then set by looking their names
up in the plists. 









The original, inline version of this code loaded a
file which contained a single ’setq’ form, but after some
consideration this interface was deemed unsatisfactory because having
the whole ’setq’ in the external file obscured the name of the
variable being set, thus removing one of the joys of ’use-package’:
all of the configuration is visible and searchable in one place.

** Installation

This package is available from [[https://melpa.org/#/][MELPA]] and extends [[https://github.com/jwiegley/use-package][use-package]]. There is
documentation at those links which explains how to set your emacs up
to use this package.

Once those work, you can install ’use-package-secret’ and its dependencies
using:

#+BEGIN_EXAMPLE
  M-x package-install RET use-package-secret RET
#+END_EXAMPLE

Now see [[*Post-Installation Tasks]].

** Installing from the Git Repository

First, use Git to clone the use-package-secret repository:

#+BEGIN_SRC shell-script
  $ git clone https://github.com/emacswatcher/use-package-secret.git /your/desired/source/path
  $ cd /your/desired/source/path/use-package-secret
#+END_SRC

Then compile the libraries and generate the info manuals:

#+BEGIN_SRC shell-script
  $ make
#+END_SRC

And then, from a privileged account, to install:

#+BEGIN_SRC shell-script
  $ make install
#+END_SRC



** license

